
slide:
	pdflatex Presentation.tex Presentation.pdf

pdf:
	pdflatex hmc.tex hmc.pdf
	biber hmc
	pdflatex hmc.tex hmc.pdf


clean:
	rm -f *.aux *.log *.fls *.fdb* *.toc *.sync* *.out *blx* *bbl *nav *snm *.bbl* *.blg pdf *.xml *.bcf